
CREATE NAMESPACE IF NOT EXISTS ae_challenge;

CREATE TABLE IF NOT EXISTS ae_challenge.gold_purchase_state_snapshot (
    snapshot_date DATE,
    snapshot_created_at TIMESTAMP,
    quality_status STRING,
    quality_flags ARRAY<STRING>,
    purchase_id BIGINT,
    purchase_partition BIGINT,
    buyer_id BIGINT,
    producer_id BIGINT,
    purchase_status STRING,
    order_date DATE,
    release_date DATE,
    gmv_date DATE,
    purchase_total_value DOUBLE,
    prod_item_id BIGINT,
    prod_item_partition BIGINT,
    product_id BIGINT,
    item_quantity INT,
    purchase_value DOUBLE,
    subsidiary STRING,
    order_transaction_cost_vat_value DOUBLE,
    order_transaction_cost_installment_value DOUBLE,
    order_transaction_cost_date DATE,
    has_purchase BOOLEAN,
    has_product_item BOOLEAN,
    has_extra_info BOOLEAN,
    has_order_transaction_cost_hist BOOLEAN,
    is_metric_eligible BOOLEAN,
    purchase_quality_status STRING,
    product_item_quality_status STRING,
    purchase_extra_info_quality_status STRING,
    order_transaction_cost_hist_quality_status STRING,
    purchase_source_transaction_datetime TIMESTAMP,
    purchase_source_transaction_date DATE,
    purchase_source_record_hash STRING,
    product_item_source_transaction_datetime TIMESTAMP,
    product_item_source_transaction_date DATE,
    product_item_source_record_hash STRING,
    purchase_extra_info_source_transaction_datetime TIMESTAMP,
    purchase_extra_info_source_transaction_date DATE,
    purchase_extra_info_source_record_hash STRING,
    order_transaction_cost_hist_source_transaction_datetime TIMESTAMP,
    order_transaction_cost_hist_source_transaction_date DATE,
    order_transaction_cost_hist_source_record_hash STRING
)
USING iceberg
PARTITIONED BY (days(snapshot_date));
